### PR TITLE
update package and fix build

### LINKED ISSUE #9: The sip directory for PyQt5 could not be located with Python3
>[ 97%] Automatic MOC for target two_render_widgets
[ 97%] Built target two_render_widgets_autogen
[ 98%] Built target two_render_widgets
[ 98%] Running SIP generator for rviz_sip Python bindings...
sip: Unable to find file "QtCore/QtCoremod.sip"
Traceback (most recent call last):
  File "/opt/ros/melodic/share/python_qt_binding/cmake/sip_configure.py", line 109, in <module>
    subprocess.check_call(cmd)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/sip', '-c', '/tmp/trizen-toreshi/ros-melodic-rviz/src/build/sip/rviz_sip', '-b', '/tmp/trizen-toreshi/ros-melodic-rviz/src/build/sip/rviz_sip/pyqtscripting.sbf', '-I', '/usr/share/sip/PyQt5', '-w', '-n', 'PyQt5.sip', '-t', 'Qt_5_14_0', '-t', 'WS_X11', 'rviz.sip']' returned non-zero exit status 1.
make[2]: *** [src/python_bindings/sip/CMakeFiles/librviz_sip.dir/build.make:95: sip/rviz_sip/Makefile] Error 1
make[1]: *** [CMakeFiles/Makefile2:4244: src/python_bindings/sip/CMakeFiles/librviz_sip.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
:: Unable to build ros-melodic-rviz - makepkg exited with code: 4

Installed `python2-sip-pyqt5 python2-pyqt5`, and it compiled fine. Fix is probably to update the dependencies for the package.

### PR DESCRIPTION
**Pull request by acxz**
resolves #9

### CODE REVIEW

**Comment by acxz** [comment]
Note: This introduces python2 but fixes the build.

**Comment by bionade24** [comment]
Looking into it, don't like the python2 deps.  We probably kicked them out at some qt package.

**Comment by acxz** [comment]
I don't like them either, but I hate people not using ROS on Arch more. We can try to resolve the issue while the package still works, instead of have Arch users wait for us.

**Comment by jwhendy** [comment]
See my latest comment on #9 for my analysis. tl;dr: I think we have a python3 compatible way forward that does not require bringing back `python2` deps.

**Comment by bionade24** [comment]
Thanks @jwhendy for the research. I now patched `ros-melodic-qt-binding`, so problems should be solved soon.

**Pull request closed without merging**
